import type { GameModeConfig } from "../types/config.types";

export const systemDesignConfig: GameModeConfig = {
  id: "system-design-builder",
  label: "System Design Builder",
  theme: {
    background: "#0B0C10",
    gridColor: "#1F2833",
    nodeColors: {
      edge: "#66FCF1",
      service: "#45A29E",
      async: "#C5C6C7",
      storage: "#66FCF1",
      delivery: "#45A29E",
    },
    accent: "#66FCF1",
    textPrimary: "#FFFFFF",
    textSecondary: "#C5C6C7",
    borderRadius: "8px",
    edgeColor: "#45A29E",
    edgeAnimatedColor: "#66FCF1",
  },
  nodeRegistry: [
    {
      id: "client",
      label: "Client",
      category: "edge",
      description: "Mobile or web client that sends and receives messages.",
      icon: "Smartphone",
      inputs: [],
      outputs: [{ id: "request", label: "Request", dataType: "request" }],
      configFields: [
        { name: "platform", label: "Platform", type: "select", options: ["mobile", "web", "both"], default: "mobile" },
      ],
    },
    {
      id: "api-gateway",
      label: "API Gateway",
      category: "edge",
      description: "Authenticates, rate-limits, and routes client traffic.",
      icon: "Globe2",
      inputs: [{ id: "request", label: "Request", dataType: "request" }],
      outputs: [{ id: "routedRequest", label: "Routed Request", dataType: "routed-request" }],
      configFields: [
        { name: "rateLimit", label: "Rate Limit", type: "number", min: 100, max: 10000, step: 100, default: 1200 },
      ],
    },
    {
      id: "chat-service",
      label: "Chat Service",
      category: "service",
      description: "Coordinates message validation, fanout, and persistence.",
      icon: "MessageSquare",
      inputs: [{ id: "routedRequest", label: "Routed Request", dataType: "routed-request" }],
      outputs: [{ id: "messageJob", label: "Message Job", dataType: "message-job" }],
      configFields: [
        { name: "replicas", label: "Replicas", type: "number", min: 1, max: 20, step: 1, default: 4 },
      ],
    },
    {
      id: "queue",
      label: "Queue",
      category: "async",
      description: "Buffers traffic spikes and keeps delivery reliable.",
      icon: "Send",
      inputs: [{ id: "messageJob", label: "Message Job", dataType: "message-job" }],
      outputs: [{ id: "persistJob", label: "Persist Job", dataType: "persist-job" }],
      configFields: [
        { name: "durable", label: "Durable", type: "toggle", default: true },
      ],
    },
    {
      id: "database",
      label: "Database",
      category: "storage",
      description: "Stores durable message and delivery state.",
      icon: "Database",
      inputs: [{ id: "persistJob", label: "Persist Job", dataType: "persist-job" }],
      outputs: [{ id: "storedMessage", label: "Stored Message", dataType: "stored-message" }],
      configFields: [
        { name: "replication", label: "Replication", type: "select", options: ["single-region", "multi-region"], default: "multi-region" },
      ],
    },
    {
      id: "notification-service",
      label: "Notification Service",
      category: "delivery",
      description: "Dispatches push notifications and delivery receipts.",
      icon: "Bell",
      inputs: [{ id: "storedMessage", label: "Stored Message", dataType: "stored-message" }],
      outputs: [{ id: "receipt", label: "Receipt", dataType: "receipt" }],
      configFields: [
        { name: "priority", label: "Priority", type: "select", options: ["normal", "high"], default: "high" },
      ],
    },
  ],
  connectionRules: {
    edge: ["edge", "service"],
    service: ["async", "storage"],
    async: ["storage", "delivery"],
    storage: ["delivery"],
    delivery: [],
  },
  canvasSettings: {
    gridSize: 20,
    snapToGrid: true,
    minZoom: 0.45,
    maxZoom: 1.5,
    edgeAnimationSpeed: 1200,
    defaultNodeSpacing: 190,
  },
  challengeMeta: {
    challengeId: "design-whatsapp-001",
    title: "Design WhatsApp for 100M users",
    description: "Build a reliable messaging path with routing, buffering, persistence, and notification delivery.",
    allowedNodeTypeIds: ["client", "api-gateway", "chat-service", "queue", "database", "notification-service"],
    maxNodes: 9,
    timeLimitSeconds: 480,
  },
};
